### ISSUE TITLE
errorDrawable 设置问题

### ISSUE THREAD

**Issue by midFang** [forJrking/ImageExt#2]
```
    var errorDrawable: Drawable?
        get() = TODO()
        set(value) {
            setDrawableOptions { placeHolderDrawable = value }
}
```
placeHolderDrawable  赋值错误了

**Comment by forJrking** [comment]
> ```
>     var errorDrawable: Drawable?
>         get() = TODO()
>         set(value) {
>             setDrawableOptions { placeHolderDrawable = value }
> }
> ```
> 
> placeHolderDrawable 赋值错误了

非常抱歉！0.0.3版本新增了全局占位图和错误图的设置方法，产生此bug，会发布新版本修复。如果有好的意见请提交，会持续维护
